#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "pathname"
require "time"
require "yaml"
require_relative "track_runs/implementation_track_runner"
require_relative "evaluation/local_run_loader"
require_relative "evaluation/metric_extractor"

repo_root = Pathname(__dir__).join("..").expand_path

batch_root = repo_root.join("experiments/protocols/implementation-track-runs/F1-phase-field-cpp")
runtime_run_root_base = batch_root.join("runtime-runs")
export_root_base = batch_root.join("exports")
protocol_output_root = batch_root.join("protocol-runs")

shared_options = {
  repo_root: repo_root,
  case_id: "F1-phase-field-cpp",
  implementation_snapshot_ref: ".kiro/methodology/dual-reviewer-spec-driven-paper/phase-field-implementation-phase-first-snapshot.md",
  upstream_spec_refs: [
    ".kiro/specs/phase-field-reverse-spec/intent.md",
    ".kiro/specs/phase-field-reverse-spec/requirements.md",
    ".kiro/specs/phase-field-reverse-spec/design.md",
    ".kiro/specs/phase-field-reverse-spec/tasks.md"
  ],
  governance_refs: [
    "dual-reviewer-rebuild/docs/coordination/implementation-conformance-review.md",
    "dual-reviewer-rebuild/docs/coordination/workflow-repair-procedure.md",
    "dual-reviewer-rebuild/docs/coordination/workflow-gate-status.md"
  ],
  case_manifest_ref: "experiments/protocols/case_manifests/F1-phase-field-cpp.yaml",
  operator: "phase-field-pilot",
  phase_profile: "tasks",
  target_id: "implementation:phase-field-cpp",
  protocol_output_root: protocol_output_root,
  runtime_run_root_base: runtime_run_root_base,
  export_root_base: export_root_base
}.freeze

single_runner = DualReviewer::TrackRuns::ImplementationTrackRunner.new(
  **shared_options,
  run_label: "F1-phase-field-cpp-single",
  review_mode: "single_review"
)

dual_runner = DualReviewer::TrackRuns::ImplementationTrackRunner.new(
  **shared_options,
  run_label: "F1-phase-field-cpp-dual",
  review_mode: "dual_reviewer_workflow"
)

single_result = single_runner.run_all
dual_result = dual_runner.run_all

loader = DualReviewer::Evaluation::LocalRunLoader.new(repo_root: repo_root)
extractor = DualReviewer::Evaluation::MetricExtractor.new

single_intake = loader.load_run(run_root: single_result.fetch("runtime_paths").fetch("review_artifact")).tap do |intake|
  intake["run_root"] = Pathname(single_result.fetch("runtime_paths").fetch("review_artifact")).dirname.to_s
end
dual_intake = loader.load_run(run_root: dual_result.fetch("runtime_paths").fetch("review_artifact")).tap do |intake|
  intake["run_root"] = Pathname(dual_result.fetch("runtime_paths").fetch("review_artifact")).dirname.to_s
end

single_metrics = extractor.extract_from_run_intake(
  run_intake: loader.load_run(run_root: Pathname(single_result.fetch("runtime_paths").fetch("review_artifact")).dirname)
)
dual_metrics = extractor.extract_from_run_intake(
  run_intake: loader.load_run(run_root: Pathname(dual_result.fetch("runtime_paths").fetch("review_artifact")).dirname)
)

comparison_summary = {
  "batch_id" => "F1-phase-field-cpp",
  "generated_at" => Time.now.utc.iso8601,
  "scope" => "phase-field pilot only",
  "comparison_modes" => [
    {
      "review_mode" => "single_review",
      "run_id" => single_result.fetch("run_id"),
      "bundle_id" => single_result.fetch("bundle_id"),
      "run_metrics" => single_metrics.fetch("run_metrics"),
      "finding_metrics" => single_metrics.fetch("finding_metrics")
    },
    {
      "review_mode" => "dual_reviewer_workflow",
      "run_id" => dual_result.fetch("run_id"),
      "bundle_id" => dual_result.fetch("bundle_id"),
      "run_metrics" => dual_metrics.fetch("run_metrics"),
      "finding_metrics" => dual_metrics.fetch("finding_metrics")
    }
  ],
  "comparison_observations" => {
    "single_total_findings" => single_metrics.dig("run_metrics", "total_findings"),
    "dual_total_findings" => dual_metrics.dig("run_metrics", "total_findings"),
    "dual_minus_single_findings" => dual_metrics.dig("run_metrics", "total_findings") - single_metrics.dig("run_metrics", "total_findings"),
    "dual_has_adversarial_role" => dual_metrics.dig("finding_metrics", "source_role_distribution", "adversarial_reviewer").to_i.positive?
  },
  "caveats" => [
    "Intent Track and Spec Track are not part of this pilot batch.",
    "Implementation findings are generated by a source-driven heuristic runtime layer for the phase-field pilot; replace this layer before claiming main-evidence-grade review quality."
  ]
}

batch_root.mkpath
(batch_root.join("batch_manifest.yaml")).write(
  YAML.dump(
    {
      "batch_id" => "F1-phase-field-cpp",
      "scope" => "phase-field pilot only",
      "protocol_output_root" => protocol_output_root.relative_path_from(repo_root).to_s,
      "runtime_run_root_base" => runtime_run_root_base.relative_path_from(repo_root).to_s,
      "export_root_base" => export_root_base.relative_path_from(repo_root).to_s,
      "run_labels" => [
        "F1-phase-field-cpp-single",
        "F1-phase-field-cpp-dual"
      ]
    }
  )
)
(batch_root.join("comparison_summary.json")).write(JSON.pretty_generate(comparison_summary))

puts JSON.pretty_generate(
  {
    "batch_id" => "F1-phase-field-cpp",
    "batch_root" => batch_root.to_s,
    "single_run_id" => single_result.fetch("run_id"),
    "dual_run_id" => dual_result.fetch("run_id"),
    "comparison_summary_path" => batch_root.join("comparison_summary.json").to_s
  }
)
