#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "pathname"
require "time"
require "yaml"
require_relative "track_runs/spec_track_writer"

repo_root = Pathname(__dir__).join("..").expand_path

batch_root = repo_root.join("experiments/protocols/spec-track-runs/F1-design-phase-field-reverse-spec")
output_root = batch_root.join("protocol-runs")

shared_options = {
  repo_root: repo_root,
  case_id: "F1-design-phase-field-reverse-spec",
  reviewed_phase: "design",
  reviewed_phase_ref: ".kiro/specs/phase-field-reverse-spec/design.md",
  adjacent_phase_refs: [
    ".kiro/specs/phase-field-reverse-spec/requirements.md",
    ".kiro/specs/phase-field-reverse-spec/tasks.md"
  ],
  alignment_refs: [
    ".kiro/methodology/dual-reviewer-spec-driven-paper/spec-track-first-case-phase-field-reverse-spec.md",
    "dual-reviewer-rebuild/docs/alignment/cross-spec-design-alignment.md"
  ],
  operator: "phase-field-design-pilot",
  output_root: output_root
}.freeze

single_writer = DualReviewer::TrackRuns::SpecTrackWriter.new(
  **shared_options,
  run_label: "F1-design-phase-field-single",
  review_mode: "single_review"
)

dual_writer = DualReviewer::TrackRuns::SpecTrackWriter.new(
  **shared_options,
  run_label: "F1-design-phase-field-dual",
  review_mode: "dual_reviewer_workflow"
)

single_paths = single_writer.write_all
dual_paths = dual_writer.write_all

single_metrics = JSON.parse(single_paths.fetch("phase_metric_snapshot").read)
dual_metrics = JSON.parse(dual_paths.fetch("phase_metric_snapshot").read)
single_alignment = YAML.load_file(single_paths.fetch("alignment_artifact"))
dual_alignment = YAML.load_file(dual_paths.fetch("alignment_artifact"))

comparison_summary = {
  "batch_id" => "F1-design-phase-field-reverse-spec",
  "generated_at" => Time.now.utc.iso8601,
  "scope" => "phase-field design pilot only",
  "comparison_modes" => [
    {
      "review_mode" => "single_review",
      "run_label" => "F1-design-phase-field-single",
      "metrics" => single_metrics.fetch("metrics"),
      "reopen_required" => single_alignment.fetch("reopen_required"),
      "propagation_targets" => single_alignment.fetch("propagation_targets"),
      "linked_signal_ids" => YAML.load_file(single_paths.fetch("signal_linkage_note")).fetch("linked_signal_ids")
    },
    {
      "review_mode" => "dual_reviewer_workflow",
      "run_label" => "F1-design-phase-field-dual",
      "metrics" => dual_metrics.fetch("metrics"),
      "reopen_required" => dual_alignment.fetch("reopen_required"),
      "propagation_targets" => dual_alignment.fetch("propagation_targets"),
      "linked_signal_ids" => YAML.load_file(dual_paths.fetch("signal_linkage_note")).fetch("linked_signal_ids")
    }
  ],
  "comparison_observations" => {
    "single_blocking_issue_count" => single_metrics.dig("metrics", "phase_blocking_issue_count"),
    "dual_blocking_issue_count" => dual_metrics.dig("metrics", "phase_blocking_issue_count"),
    "single_reopen_required" => single_alignment.fetch("reopen_required"),
    "dual_reopen_required" => dual_alignment.fetch("reopen_required"),
    "single_handback_class_b" => single_metrics.dig("metrics", "phase_handback_count_by_class", "B"),
    "dual_handback_class_b" => dual_metrics.dig("metrics", "phase_handback_count_by_class", "B"),
    "dual_intent_attributed_issue_count" => dual_metrics.dig("metrics", "phase_intent_attributed_issue_count"),
    "dual_major_correction_count" => dual_metrics.dig("metrics", "phase_major_correction_count")
  },
  "caveats" => [
    "This batch covers the design phase only; intent, requirements, tasks, and implementation evidence remain separate pilot artifacts.",
    "Design findings are generated by a source-driven heuristic runner for the phase-field design case and should be treated as pilot acquisition evidence."
  ]
}

batch_root.mkpath
(batch_root.join("batch_manifest.yaml")).write(
  YAML.dump(
    {
      "batch_id" => "F1-design-phase-field-reverse-spec",
      "scope" => "phase-field design pilot only",
      "output_root" => output_root.relative_path_from(repo_root).to_s,
      "run_labels" => [
        "F1-design-phase-field-single",
        "F1-design-phase-field-dual"
      ]
    }
  )
)
(batch_root.join("comparison_summary.json")).write(JSON.pretty_generate(comparison_summary))

puts JSON.pretty_generate(
  {
    "batch_id" => "F1-design-phase-field-reverse-spec",
    "batch_root" => batch_root.to_s,
    "comparison_summary_path" => batch_root.join("comparison_summary.json").to_s
  }
)
